config/routes.rb
Rails.application.routes.draw do
  resources :migrations
  root 'businesses#index', as: 'businesses_index'

  resources :businessunits, :transactionunits, :activeunits
  resources :businessflows, :transactionflows, :activeflows


  resources :resources do
    get 'search', on: :collection
  end

  resources :resourceslines

  resources :businesses do
    resources :businessflows
  end



  resources :actives do
    resources :resourceslines
    get 'clone', on: :member
    get 'copyform', on: :member
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [:show, :edit, :update, :destroy]

  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = Business.all
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
  end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(business_params)

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.require(:business).permit(:code, :name, :businessflow_id, :status, :remarks)
    end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%= form_with(model: business, local: true) do |form| %>
  <% if business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% business.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card-header bg-transparent border-first">
    <div class="card-block">
      <h6 class="card-title"><%= @business.businessflow.name %>: <%= @business.id %></h6>


      <div class="d-flex flex-column flex-sm-row-2">
        <div class="p-1 form-group row">
          <label for="business_code" class="col-sm-2 col-form-label">代码</label>
          <div class="col-sm-9 ">
            <!-- <input type="text" class="form-control" id="business_code"  placeholder=<%= form.text_field :code %> -->
            <%= form.text_field :code %>
          </div>
        </div>
        <div class="p-1 form-group row">
          <label for="business_name" class="col-sm-2 col-form-label">名称</label>
          <div class="col-sm-9">
            <!-- <input type="text" class="form-control" id="business_name"  placeholder=<%= form.text_field :name %> -->
            <%= form.text_field :name %>
          </div>
        </div>

        <!-- <div class="form-group">
         <label for="exampleFormControlSelect1">Example select</label>
         <select class="form-control" id="exampleFormControlSelect1">
           <option>1</option>
           <option>2</option>
           <option>3</option>
           <option>4</option>
           <option>5</option>
         </select>
        </div> -->

        <!-- <div class="form-group">
          <label for="businessflow_id" class="col-sm-2 col-form-label">Businessflow</label>
          <select class="form-control" id="businessflow_id" name="business[businessflow_id]">
           <% Businessflow.all.collect do |p| %>
             <option value="<%= p.id %>"><%= p.name %></option>
           <% end %>
          </select>
        </div> -->

        <div class="p-1 form-group row">
          <div class="col-sm-2">
            <%= form.label :类型 %>
          </div>
          <div class="col-sm-9">
            <%= form.select :businessflow_id, Businessflow.all.collect {|p| [ p.name, p.id ] } %>
          </div>
        </div>

        <div class="p-1 form-group row">
          <div class="col-sm-2"><%= form.label :状态 %></div>
          <div class="col-sm-9">
              <%= form.select :status, Business.statuses.keys, prompt: "select a type"%>
          </div>
        </div>

        <!-- <div class="form-group row">
          <div class="col-sm-2"><%= form.label :日期 %></div>
          <div class="col-sm-9">
              <%= form.date_select :created_at %>
          </div>
        </div> -->

        <div class="p-1 form-group row">
          <label for="business_remarks" class="col-sm-2 col-form-label">备注</label>
          <div class="col-sm-9">
            <!-- <input type="text" class="form-control" id="business_remarks"  placeholder=<%= form.text_field :remarks %> -->
            <%= form.text_field :remarks %>
          </div>
        </div>

      </div>

    </div>
  </div>

  <div class="card-footer bg-transparent border-first">
    <button type="submit" class="btn btn-primary">更新</button>
  </div>



<!--
  <div class="actions">
    <button type="submit" class="btn btn-primary">更新</button>
  </div> -->


<% end %>

app/views/businesses/_form0.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %>
      prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, size: 40 %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_area :address, rows: 3, cols: 40 %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email, size: 40 %>
  </div>

  <div class="field">
    <%= f.label :pay_type %>
    <%= f.select :pay_type, Order.pay_types.keys,
                  prompt: 'Select a payment method' %>
  </div>

  <div class="actions">
    <%= f.submit 'Place Order' %>
  </div>
<% end %>


<!-- Swift Lessons -->
<section class="section section-swift-lessons" data-analytics-section-engagement="name:swift-lessons">
<div class="section-content">
<h2 class="section-headline typography-section-headline">各种课程，让孩子们通过 Swift <br class="hide-for-small"/>开始思考、解决问题、发挥创意。</h2>
<p class="section-intro">我们开创了一系列标准化教材来帮助你教授编程，包括课堂活动，基于 app 的谜题和讨论话题。下面我们就来快速预览一下在 iPad 上讲授 Swift 的课程。</p>
<div class="subsection-content swift-lessons-tabs gallery-container" data-component-list="TabGallery">
<div
  data-ac-gallery-tabnav="swift-lessons-gallery"
  class="tabs-nav tabnav column large-12"
>
  <ul class="tabnav-items" role="tablist">
    <li class="tabnav-item" role="presentation">
      <a
        href="#swift-gallery-creating-sequences"
        id="swift-gallery-creating-sequences-trigger"
        data-ac-gallery-trigger="swift-gallery-creating-sequences"
        class="tabnav-link current"
      >创建序列</a>
    </li><!--
 --><li class="tabnav-item" role="presentation">
      <a
        href="#swift-gallery-think-like-computer"
        id="swift-gallery-think-like-computer-trigger"
        data-ac-gallery-trigger="swift-gallery-think-like-computer"
        class="tabnav-link"
      >像电脑一样思考</a>
    </li><!--
 --><li class="tabnav-item" role="presentation">
      <a
      href="#swift-gallery-algorithms"
      id="swift-gallery-algorithms-trigger"
      data-ac-gallery-trigger="swift-gallery-algorithms"
      class="tabnav-link"
      >算法</a>
    </li><!--
 --><li class="tabnav-item" role="presentation">
      <a
        href="#swift-gallery-logical-thinking"
        id="swift-gallery-logical-thinking-trigger"
        data-ac-gallery-trigger="swift-gallery-logical-thinking"
        class="tabnav-link"
      >逻辑思维</a>
    </li><!--
 --><li class="tabnav-item" role="presentation">
      <a
        href="#swift-gallery-creating-worlds"
        id="swift-gallery-creating-worlds-trigger"
        data-ac-gallery-trigger="swift-gallery-creating-worlds"
        class="tabnav-link"
      >创造新的世界</a>
    </li>
  </ul>
</div>
<div
  id="swift-lessons-gallery"
  data-ac-gallery-slide

  class="gallery-slides column large-10 large-offset-1 medium-12 medium-offset-0"
>
  <div id="swift-gallery-creating-sequences" data-ac-gallery-item class="column large-12 gallery-slide">
    <figure class="gallery-image column large-4 small-12" aria-hidden="true">
      <figcaption class="visuallyhidden">创建序列</figcaption>
    </figure>
    <div class="gallery-text column large-7 small-12">
      <p>小学生们自己编排疯狂的舞步，然后教其他学生如何表演这些舞步。在这个过程中，他们将了解到正确编排指令顺序的重要意义，然后在 codeSpark 和 Tynker 这类可视化应用中练习编程。</p>
    </div>
  </div>
  <div id="swift-gallery-think-like-computer" data-ac-gallery-item class="column large-12 gallery-slide">
    <figure class="gallery-image column large-4 small-12" aria-hidden="true">
      <figcaption class="visuallyhidden">像电脑一样思考</figcaption>
    </figure>
    <div class="gallery-text column large-7 small-12">
      <p>组织学生玩藏东西的游戏，让学生们将一件物品藏起来，然后录制一段他们自己按特定顺序 (序列) 指示具体方向 (命令) 的视频，帮助另一位学生找到该物品。这种动手实践活动将让全班同学明白电脑到底是怎样接受指令的。</p>
    </div>
  </div>
  <div id="swift-gallery-algorithms" data-ac-gallery-item class="column large-12 gallery-slide">
    <figure class="gallery-image column large-4 small-12" aria-hidden="true">
      <figcaption class="visuallyhidden">算法</figcaption>
    </figure>
    <div class="gallery-text column large-7 small-12">
      <p>在“谁是最高的人”游戏中，学生们将学习如何创建算法来找出班里最高的同学。这个活动将教学生们如何制订分步规则去完成一个目标，就像代码告诉电脑做什么一样。</p>
    </div>
  </div>
  <div id="swift-gallery-logical-thinking" data-ac-gallery-item class="column large-12 gallery-slide">
    <figure class="gallery-image column large-4 small-12" aria-hidden="true">
      <figcaption class="visuallyhidden">逻辑思考</figcaption>
    </figure>
    <div class="gallery-text column large-7 small-12">
      <p>学生们拍下教室里各种物品的照片，并围绕一个条件，比如某个形状或颜色，将照片拼贴在一起。然后，他们将拼贴照片展示给其他小组，让这些小组猜测拼贴所围绕的条件是什么。这让他们有机会去审视自己创建的条件是否清楚，而清楚的条件是编写高效代码必不可少的一部分。</p>
    </div>
  </div>
  <div id="swift-gallery-creating-worlds" data-ac-gallery-item class="column large-12 gallery-slide">
    <figure class="gallery-image column large-4 small-12" aria-hidden="true">
      <figcaption class="visuallyhidden">创造新的世界</figcaption>
    </figure>
    <div class="gallery-text column large-7 small-12">
      <p>学生们可以使用迄今为止所学的 Swift 代码，在 Swift Playgrounds 中创造自己的世界和谜题。他们将通过更改宝石、据点和人物来练习根据自己的想法构建他们的世界，并使用数组跟踪这些元素。然后，他们可以与朋友分享他们完成的作品。</p>
    </div>
  </div>
</div>
</div>

<!--div class="tout column large-4 large-offset-2 small-12 small-offset-0">
  <p class="typography-label">学习编程 3</p>
  <p class="typography-subbody large-11 medium-12">在<i>《学习编程 3》</i>中，你的学生将拓展他们的编程技能，开始更像 app 开发者那样去思考。他们将探索专业开发者使用的强大编程概念，并运用这些概念打造一系列创意工具。另外，他们还将学习如何放置和操纵图像来创造新的世界。</p>
  <a class="block download-link medium-extend-13 swift-lessons-download-link-code-3" href="https://itunes.apple.com/book/id1173709121?v0=www-us-education-everyone-can-code-book-ltc3-teacher-guide">
    <figure class="download-icon"></figure>
    <p class="download-cta block-link icon typography-subbody">下载<span class="visuallyhidden">《学习编程 3》</span>的教师指南<span class="icon icon-after icon-external" aria-hidden="true"></span></p>
  </a>
</div-->
</div>
</div>
</section>
<!-- END: Swift Lessons -->

app/views/businesses/edit.html.erb
<div class="card-header bg-transparent border-first">
  <h5>商务编辑</h5>
</div>


<%= render 'form', business: @business %>

<div class="card-footer bg-transparent border-first">
  <%= link_to '显示', @business %> |
  <%= link_to '列表', businesses_path %>
</div>

app/views/businesses/index.html.erb
<p id="notice"><%= notice %></p>

<h5>商务</h5>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">序</th>
      <th scope="col">编号</th>
      <th scope="col">名称</th>
      <th scope="col">类型</th>
      <!-- <th scope="col">状态</th> -->
      <th scope="col">备注</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @businesses.each do |business| %>
      <tr>
        <th scope="row"><%= link_to business.id,business %></th>
        <td ><%= business.code %></td>
        <td ><%= business.name %></td>
        <td ><%= business.businessflow.name %></td>
        <!-- <td ><%= business.status %></td> -->
        <td ><%= business.remarks %></td>
        <!-- <td><%= link_to 'Show', business %></td>
        <td><%= link_to 'Edit', edit_business_path(business) %></td> -->
        <td><%= link_to 'D', business_path(business), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新建', new_business_path %>

app/views/businesses/ls.html.erb
<p><!--  --></p>
<%= render(@businessflow.transactionflows) %>

<%= render 'transactionflows', order: @transactionflow %>

<p><%= render (transactionflow.activeflows) %></p>

app/views/businesses/new.html.erb
<h1>New Business</h1>

<%= render 'form', business: @business %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<div class="card bg-light mb-3">

  <p id="notice"><%= notice %></p>

  <div class="card-header  border-first">
    <div class="card-block">
      <h5 class="card-title"><%= @business.businessflow.name %>: <%= @business.id %></h5>


      <div class="p-1 form-group row">
        <div class="col-sm-4">代码：<%= @business.code %></div>
        <div class="col-sm-4">名称：<%= @business.name %></div>
        <div class="col-sm-4">状态：<%= @business.status %></div>
        <div class="col-sm-4">日期：<%= @business.created_at.to_s(:mdy) %></div>
        <div class="col-sm-4">备注：<%= @business.remarks %></div>
        <div class="col-sm-4 d-none d-sm-block">桌面显示</div>
      </div>

    </div>
  </div>

  <div class="card-body text-first border-first">
    <!-- 页签标题 -->
    <ul id="mytab" class="nav nav-pills flex-sm-row">
      <% @business.businessflow.transactionflows.each do |transactionflows| %>
      <li  class="nav-item">
        <a class="nav-link" href="#<%= transactionflows.transactionunit.name %>" data-toggle="tab"><%= transactionflows.transactionunit.name %></a>
      </li>
      <% end %>
    </ul>
    <p></p>
    <div class="tab-content"> <!--1 商务下的交易集，定义交易控件名称，关联交易标题 -->
       <% @business.businessflow.transactionflows.each do |transactionflows| %>
         <% if transactionflows.floworderid == 1 %>
         <div class="tab-pane active" id="<%= transactionflows.transactionunit.name %>"><!--2 每个交易下的活动集 -->   <!--3 每个活动标题下的实例活动 -->
         <% else %>
         <div class="tab-pane" id="<%= transactionflows.transactionunit.name %>">
         <% end %><hr>
         <table>
           <tbody>
             <tr >
               <% transactionflows.activeflows.order("floworderid").each do |activeflows| %>
                 <td  class="text-info align-self-start">
                   <h6><%= activeflows.activeunit.name %></h6>
                </td>
               <% end %>
             </tr>
             <tr >
               <% transactionflows.activeflows.order("floworderid").each do |activeflows| %>

                 <td  class="text-info align-self-start">
                  <% @business.actives.select("DISTINCT active_id as id,activeflow_id")
                  .where(activeflow_id: activeflows.id).order("id").each do |actives| %>

                  <% if actives.sum_openqty_total > 0 %>
                   <button type="button" class="btn btn-success btn-sm">
                    <%= activeflows.activeunit.name %>
                    <span class="badge badge-light">
                      <%=  link_to actives.id , actives %></span>
                   </button><%= "->" %><p></p>
                  <% else %>
                   <button type="button" class="btn btn-danger btn-sm">
                    <%= activeflows.activeunit.name %>
                    <span class="badge badge-light">
                      <%=  link_to actives.id , actives %></span>
                   </button><%= "->" %><p></p>
                  <% end %>





                  <% end %>
                </td>
               <% end %>
             </tr>

           </tbody>
         </table>

         </div>
       <% end %>
     </div>

  </div>

  <div class="card-footer bg-transparent border-first">
    <%= link_to '编辑', edit_business_path(@business) %> |
    <%= link_to '列表', businesses_path %>
  </div>

</div>