config/routes.rb
Rails.application.routes.draw do
  resources :migrations
  root 'businesses#index', as: 'businesses_index'

  resources :businessunits, :transactionunits, :activeunits
  resources :businessflows, :transactionflows, :activeflows


  resources :resources do
    get 'search', on: :collection
  end

  resources :resourceslines

  resources :businesses do
    resources :businessflows
  end



  resources :actives do
    resources :resourceslines
    get 'clone', on: :member
    get 'copyform', on: :member
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/active.rb
class Active < ApplicationRecord

  enum status: {
    "草稿"        => 1,
    "正式"         => 2,
    "关闭"        => 3
  }
  validates :status, inclusion: statuses.keys

  belongs_to :activeflow
  belongs_to :resource
  has_many :resourceslines
  has_many :businesses, :through => :resourceslines


  def sum_quan_total
    # line_items.to_a.sum { |item| item.total_price }
    resourceslines.to_a.sum { |resourcesline| resourcesline.quantity }
  end

  def sum_openqty_total
    # line_items.to_a.sum { |item| item.total_price }
    resourceslines.to_a.sum { |resourcesline| resourcesline.openqty }
  end

  def sum_price_total
    # line_items.to_a.sum { |item| item.total_price }
    resourceslines.to_a.sum { |resourcesline| resourcesline.price_total }
  end

  def sum_vat_price_total
    # line_items.to_a.sum { |item| item.total_price }
    resourceslines.to_a.sum { |resourcesline| resourcesline.vat_price_total }
  end

  def sum_cost_total
    # line_items.to_a.sum { |item| item.total_price }
    resourceslines.to_a.sum { |resourcesline| resourcesline.cost_total }
  end

  def sum_vat_cost_total
    # line_items.to_a.sum { |item| item.total_price }
    resourceslines.to_a.sum { |resourcesline| resourcesline.vat_cost_total }
  end

  def add_old_resourceslines(active)
    active.resourceslines.each do |old_resourceslines|

      new_record = old_resourceslines.dup
      new_record.quantity = new_record.openqty
      new_record.baseid = old_resourceslines.id
      # new_record.price = 20.00
      resourceslines << new_record
      # resourceslines << old_resourceslines
      # active.resourceslines << old_resourceslines
      # old_resourceslines.openqty = 0
      @resourcesline = Resourcesline.find(old_resourceslines.id)
      @resourcesline.openqty = 0
      @resourcesline.save

      # throw :abort
    end


  end

  def update_old_resourceslines(active)

    active.resourceslines.each do |old_resourceslines|
      # new_record = old_resourceslines.dup
      # new_record.openqty = 0
      # # new_record.price = 20.00
      # resourceslines << new_record


      # old_resourceslines.openqty = 0

      # throw :abort
    end

  end



end

app/controllers/actives_controller.rb
class ActivesController < ApplicationController
  before_action :set_active, only: [:show, :edit, :update, :destroy]

  # GET /actives
  # GET /actives.json
  def index
    @actives = Active.all
  end

  # GET /actives/1
  # GET /actives/1.json
  def show
  end

  # GET /actives/new
  def new
    @active = Active.new
    # new_record = old_record.dup
    # new_active = old_active.dup
    # @active.add_old_resourceslines(active_params)
  end

  # GET /actives/copyfrom
  def copyform
    @active = Active.new
  end

  # GET /actives/clone
  def clone
    @old_active = Active.find(params[:id]) # find original object
    @active = Active.new(@old_active.attributes) # initialize duplicate (not saved)
    @active.id = nil
    @active.activeflow_id = @old_active.activeflow.afteractiveunit_id
    @active.save
    @active.add_old_resourceslines(@old_active)
    # update_old_resourceslines(@old_active)

    render :edit # render same view as "new", but with @prescription attributes already filled in
  end

  # def update_old_resourceslines(active)
  #   active.resourceslines.each do |old_resourceslines|
  #     # Active.resourceslines << old_resourceslines
  #     # puts old_resourceslines
  #     # @resourcesline = @active.resourceslines.create(old_resourceslines)
  #     puts old_resourceslines.openqty
  #
  #     @resourcesline = Resourcesline.find(old_resourceslines.id)
  #     @resourcesline.openqty = 0
  #     @resourcesline.save
  #
  #
  #
  #     # old_resourceslines.openqty = 0
  #     # render html: "old_resourceslines.name"
  #     # format.html { "ee" }
  #     # @active.resourceslines.new << old_resourceslines
  #     # throw :abort
  #   end
  # end

  # GET /actives/1/edit
  def edit
  end

  # POST /actives
  # POST /actives.json
  def create
    @active = Active.new(active_params)
    respond_to do |format|
      if @active.save
        puts @active.id
        format.html { redirect_to @active, notice:  'Active was successfully created.' }
        format.json { render :show, status: :created, location: @active }
      else
        format.html { render :new }
        format.json { render json: @active.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actives/1
  # PATCH/PUT /actives/1.json
  def update
    respond_to do |format|
      if @active.update(active_params)
        format.html { redirect_to @active, notice: 'Active was successfully updated.' }
        format.json { render :show, status: :ok, location: @active }
      else
        format.html { render :edit }
        format.json { render json: @active.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actives/1
  # DELETE /actives/1.json
  def destroy
    @active.destroy
    respond_to do |format|
      format.html { redirect_to actives_url, notice: 'Active was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_active
      @active = Active.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def active_params
      params.require(:active).permit(:activeflow_id, :resource_id, :status, :remarks)
    end



end

app/helpers/actives_helper.rb
module ActivesHelper
end

app/views/actives/_form.html.erb
<%= form_with(model: active, local: true) do |form| %>
  <% if active.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(active.errors.count, "error") %> prohibited this active from being saved:</h2>

      <ul>
      <% active.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card-header bg-transparent border-first">
    <div class="card-block">
      
      <div class="d-flex flex-column flex-sm-row-2">
        <div class="p-1 form-group row">
          <!-- <div class="col-sm-2">
            <%= form.label :类型 %>
          </div> -->
          <div class="col-sm-4 ">
            类型：<%= form.select :activeflow_id,Activeflow.all.collect {|p| [ p.activeunit.name, p.id ] } %>
          </div>
          <div class="col-sm-4 ">
            客户：<%= form.select :resource_id,
            Resource.all.collect {|p| [ p.name, p.id ] } %>
          </div>
          <div class="col-sm-4">
              状态：<%= form.select :status, Active.statuses.keys, prompt: "select a type"%>
          </div>
          <div class="col-sm-4 d-none d-sm-block">
              桌面显示
          </div>


        </div>
      </div>
    </div>
  </div>

  <div class="card-body text-first border-first">
    <table class="table table-sm table-striped">

     <thead class="thead-dark">
      <tr>
        <!-- <th scope="col"><div class="d-inline p-1">序</div></th> -->
        <th scope="col"><div class="d-inline ">代码</div></th>
        <th scope="col"><div class="d-inline ">资源</div></th>
        <th scope="col"><div class="d-inline ">数量</div></th>
        <th scope="col"><div class="d-inline">价格</div></th>
        <th scope="col"><div class="d-inline ">合计</div></th>
        <th scope="col"><div class="d-none d-sm-inline ">成本价</div></th>
        <th scope="col"><div class="d-none d-sm-inline ">成本合计</div></th>
        <th scope="col"><div class="d-none d-sm-inline ">税率</div></th>
        <th scope="col"><div class="d-none d-sm-inline ">仓库</div></th>
        <th scope="col"><div class="d-none d-sm-inline ">状态</div></th>
      </tr>
     </thead>

     <tbody>
      <% @active.resourceslines.each do |resourcesline| %>
       <tr>
         <!-- <th scope="row">
           <div class="d-inline">
             <%= link_to resourcesline.id, edit_active_resourcesline_path(resourcesline.active, resourcesline) %>
           </div>
         </th> -->
         <td>
           <div class="d-inline">
             <%= link_to resourcesline.resource.code, edit_active_resourcesline_path(resourcesline.active, resourcesline)  %>
           </div>
         </td>
         <td><div class="d-inline"><%= resourcesline.resource.name %></div></td>
         <td><div class="d-inline"><p class="text-right"><%= resourcesline.quantity %></p></div></td>
         <td><div class="d-inline"><p class="text-right"><%= sprintf("%0.02f",resourcesline.price) %></p></div></td>
         <td><div class="d-inline"><p class="text-right"><%= sprintf("%0.02f",resourcesline.price_total) %></p></div></td>

         <td><div class="d-none d-sm-inline"><p class="text-right"><%= sprintf("%0.02f",resourcesline.cost) %></p></div></td>
         <td><div class="d-none d-sm-inline"><p class="text-right"><%= sprintf("%0.02f",resourcesline.cost_total) %></p></div></td>
         <td><div class="d-none d-sm-inline"><p class="text-right"><%= resourcesline.vatgroup %></p></div></td>
         <td><div class="d-none d-sm-inline"><p class="text-right"><%= resourcesline.whscode %></p></div></td>
         <td><div class="d-none d-sm-inline"><p class="text-right"><%= resourcesline.status %></p></div></td>
         <td><%= link_to 'D', [resourcesline.active, resourcesline],
         method: :delete, data: { confirm: 'Are you sure?' } %></td>


         <!-- <td><%= link_to 'E', resourcesline %></td> -->
         <!-- <td><%= link_to 'Edit', edit_active_resourcesline_path(resourcesline.active, resourcesline)  %></td> -->
         <!-- <td><%= link_to 'D', [resourcesline.active, resourcesline],
         method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
       </tr>
      <% end %>
     </tbody>

     <tfoot>
      <tr >
       <!-- <th scope="col"><div class="d-inline"></div></th> -->
       <th scope="col"><div class="d-inline">总计</div></th>
       <th scope="col"><div class="d-inline"></div></th>
       <th scope="col"><div class="d-inline"><p class="text-right"><%=  @active.sum_quan_total %></p></div></th>
       <th scope="col"><div class="d-inline"><p class="text-right"></p></div></th>
       <th scope="col"><div class="d-inline"><p class="text-right"><%=  sprintf("%0.02f", @active.sum_price_total) %></p></div></th>
       <th scope="col"><div class="d-none d-sm-inline"></div></th>
       <th scope="col"><div class="d-none d-sm-inline"><p class="text-right"><%=  sprintf("%0.02f", @active.sum_cost_total) %></p></div></th>
       <th scope="col"><div class="d-none d-sm-inline"></div></th>
       <th scope="col"><div class="d-none d-sm-inline"></div></th>
       <th scope="col"><div class="d-none d-sm-inline"></div></th>


      </tr>

     </tfoot>

    </table>
  </div>

  <div class="card-footer bg-transparent border-first">
    <div class="p-1 form-group row">
      <label class="col-sm-2 col-form-label">备注</label>
      <div class="col-sm-9">
        <%= form.text_field :remarks %>
      </div>
    </div>

    <button type="submit" class="btn btn-primary">活动更新</button>

  </div>

  <!-- <div class="form-field-user-address">
  <%= form.select :resource, collection: Resource.all.collect {|p| [ p.name, p.id ] } %>
  </div>
   <%= link_to '新增资源', new_resource_path, remote: true %> -->

<% end %>

app/views/actives/edit.html.erb
<div class="card-header bg-transparent border-first">
  <h5>活动编辑</h5>
</div>

<%= render 'form', active: @active %>
<!-- 下面少一个“=” -->
<!-- <% render @active.resourceslines %> -->
<div class="card-footer bg-transparent border-first">
  <%= render "resourceslines/table" %>
  <%= link_to '显示', @active %> |
  <%= link_to '列表', actives_path %>
</div>

app/views/actives/index.html.erb
<p id="notice"><%= notice %></p>

<h5>活动</h5>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th>序</th>
      <th>类型</th>
      <th>交易方</th>
      <th>状态</th>
      <th>备注</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>


    <%  @actives.each do |active| %>
      <tr>
        <td><%= link_to active.id, active %></td>
        <td><%= active.activeflow.activeunit.name %></td>
        <td><%= active.resource.name %></td>
        <td><%= active.status %></td>
        <td><%= active.remarks %></td>
        <td><%= active.resourceslines.count %></td>
        <td><%= active.sum_price_total %></td>
        <td><%= active.sum_openqty_total %></td>
        <!-- <td><%= link_to 'Show', active %></td>
        <td><%= link_to 'Edit', edit_active_path(active) %></td> -->
        <td><%= link_to 'Destroy', active, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>

</table>

<br>

<%= link_to 'New Active', new_active_path %>

app/views/actives/new.html.erb
<h1>New Active</h1>

<%= render 'form', active: @active %>

<%= link_to 'Back', actives_path %>

app/views/actives/show.html.erb
<div class="card bg-info mb-3">
  <div class="card-header bg-transparent border-first">
    <div class="card-block">

      <% @active.businesses.select("DISTINCT businesses.id,businesses.name,businessflow_id").each do |businesses| %>
      <p><span class="badge badge-light">项目</span>
        <button type="button" class="btn btn-info btn-sm">
         <span class="badge badge-light"><%= link_to businesses.name,business_path(businesses.id) %></span>
        </button>
      </p>


         <h5 class="badge badge-info">

           <% businesses.businessflow.transactionflows.each do |transactionflows| %>
             <td><%= transactionflows.transactionunit.name %>:</td>
             <% transactionflows.activeflows.order("floworderid").each do |activeflows| %>
               <td  class="text-info ">
                 <% if activeflows.activeunit.name == @active.activeflow.activeunit.name %>
                  <button type="button" class="btn btn-light btn-sm">
                    <span>qq:<%= activeflows.activeunit.name %>--></span>
                   </button>


                <% else %>
                  <%= activeflows.activeunit.name %>-->
                 <% end %>

              </td>
             <% end %>
          <% end %>

        </h5>
      <% end %>




    </div>
  </div>

  <div class="card-body text-first border-first">
    <div class="card-footer bg-transparent border-first">
      <div class="p-1">备注：<%= @active.remarks %><br></div>
      <%= link_to '编辑', edit_active_path(@active) %> |
      <%= link_to '列表', actives_path %> |
      <!-- <%= link_to '复制从', edit_active_path(@active) %> | -->
       <% if @active.sum_openqty_total > 0 %>

      <%= link_to '下一步', clone_active_path(@active) %>:<%= @active.activeflow.afteractiveflow.activeunit.name %>
      <!-- <%= link_to '复制从', copyform_active_path(@active) %> -->
      <% else %>
      <%= '' %>-->
      <% end %>

    </div>
    <!-- active -->
    <div class="card bg-light mb-3">
      <p id="notice"><%= notice %></p>
      <div class="card-header bg-transparent border-first">
        <div class="card-block">

          <h5 class="card-title"><%= @active.activeflow.activeunit.name %>: <%= @active.id %></h5>

          <div class="p-1 form-group row">
            <div class="col-sm-4"><%= @active.resource.code %>：<%= @active.resource.name %></div>
            <div class="col-sm-4">销售部：张峰</div>
            <div class="col-sm-4">状态：<%= @active.status %></div>
            <div class="col-sm-4">日期：<%= @active.created_at.to_s(:mdy) %></div>

            <div class="col-sm-4 d-none d-sm-block">桌面显示</div>
          </div>



        </div>
      </div>
      <div class="card-body text-first border-first">
        <table class="table table-sm table-striped">
         <thead class="thead-dark">
          <tr>
            <!-- <th scope="col"><div class="d-inline p-1">序</div></th> -->
            <th scope="col"><div class="d-inline ">代码</div></th>
            <th scope="col"><div class="d-inline ">资源</div></th>
            <th scope="col"><div class="d-inline ">数量</div></th>
            <th scope="col"><div class="d-inline">价格</div></th>
            <th scope="col"><div class="d-inline ">合计</div></th>
            <th scope="col"><div class="p-0 d-none d-sm-inline ">成本价</div></th>
            <th scope="col"><div class="p-0 d-none d-sm-inline ">成本合计</div></th>
            <th scope="col"><div class="d-none d-sm-inline ">税率</div></th>
            <th scope="col"><div class="d-none d-sm-inline ">仓库</div></th>
            <th scope="col"><div class="d-none d-sm-inline ">状态</div></th>
          </tr>
         </thead>
         <tbody>
          <% @active.resourceslines.each do |resourcesline| %>
           <tr>
             <!-- <th scope="row">
               <div class="d-inline">
                 <%= link_to resourcesline.id, edit_active_resourcesline_path(resourcesline.active, resourcesline) %>
               </div>
             </th> -->
             <td>
               <div class="d-inline">
                 <%= link_to resourcesline.resource.code, edit_active_resourcesline_path(resourcesline.active, resourcesline)  %>
               </div>
             </td>
             <td><div class="d-inline"><%= resourcesline.resource.name %></div></td>
             <td><div class="d-inline"><p class="text-right"><%= resourcesline.quantity %></p></div></td>
             <td><div class="d-inline"><p class="text-right"><%= sprintf("%0.02f",resourcesline.price) %></p></div></td>
             <td><div class="d-inline"><p class="text-right"><%= sprintf("%0.02f",resourcesline.price_total) %></p></div></td>

             <td><div class="d-none d-sm-inline"><p class="text-right"><%= sprintf("%0.02f",resourcesline.cost) %></p></div></td>
             <td><div class="d-none d-sm-inline"><p class="text-right"><%= sprintf("%0.02f",resourcesline.cost_total) %></p></div></td>
             <td><div class="d-none d-sm-inline"><p class="text-right"><%= resourcesline.vatgroup %></p></div></td>
             <td><div class="d-none d-sm-inline"><p class="text-right"><%= resourcesline.whscode %></p></div></td>
             <td><div class="d-none d-sm-inline"><p class="text-right"><%= resourcesline.status %></p></div></td>


             <!-- <td><%= link_to 'E', resourcesline %></td> -->
             <!-- <td><%= link_to 'Edit', edit_active_resourcesline_path(resourcesline.active, resourcesline)  %></td> -->
             <!-- <td><%= link_to 'D', [resourcesline.active, resourcesline],
             method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
           </tr>
          <% end %>
         </tbody>
         <tfoot>
          <tr >
           <!-- <th scope="col"><div class="d-inline"></div></th> -->
           <th scope="col"><div class="d-inline">总计</div></th>
           <th scope="col"><div class="d-inline"></div></th>
           <th scope="col"><div class="d-inline"><p class="text-right"><%=  @active.sum_quan_total %></p></div></th>
           <th scope="col"><div class="d-inline"><p class="text-right"></p></div></th>
           <th scope="col"><div class="d-inline"><p class="text-right"><%=  sprintf("%0.02f", @active.sum_price_total) %></p></div></th>
           <th scope="col"><div class="d-none d-sm-inline"></div></th>
           <th scope="col"><div class="d-none d-sm-inline"><p class="text-right"><%=  sprintf("%0.02f", @active.sum_cost_total) %></p></div></th>
           <th scope="col"><div class="d-none d-sm-inline"></div></th>
           <th scope="col"><div class="d-none d-sm-inline"></div></th>
           <th scope="col"><div class="d-none d-sm-inline"></div></th>


          </tr>
         </tfoot>
        </table>
      </div>

    </div>
  </div>
</div>