config/routes.rb
Rails.application.routes.draw do
  resources :migrations
  root 'businesses#index', as: 'businesses_index'

  resources :businessunits, :transactionunits, :activeunits
  resources :businessflows, :transactionflows, :activeflows


  resources :resources do
    get 'search', on: :collection
  end

  resources :resourceslines

  resources :businesses do
    resources :businessflows
  end



  resources :actives do
    resources :resourceslines
    get 'clone', on: :member
    get 'copyform', on: :member
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/resources/_form.html.erb
<%= form_with(model: resource, local: true) do |form| %>
  <% if resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code, id: :resource_code %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :resource_name %>
  </div>

  <div class="field">
    <%= form.label :resourcetype1 %>
    <%= form.select :resourcetype, Resource.resourcetypes.keys,
                  prompt: "select a type" %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/resources/_formajax.html.erb
a<%= form_for(@resource) do |form| %>


  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code, id: :resource_code %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :resource_name %>
  </div>

  <div class="field">
    <%= form.label :resourcetype %>
    <%= form.select :resourcetype, Resource.resourcetypes.keys,
                  prompt: "select a type" %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/resources/create.js.erb
<% if @resource.errors.blank? %>
  // 用 Ajax 载入当前页面，找到下拉框的 Dom 的新 HTML，再替换目前页面的下拉框 Dom
  var selector = '.form-field-user-address';
  $.get(location.href, function(html) {
    var doc = $(html).find(selector);
    $(selector).replaceWith(doc);
  });
  bootbox.hideAll();
<% else %>
  var html = "<%= j(render('form', remote: true)) %>";
  // 保存失败，直接替换浮动窗口上面的 HTML 为新的 form render 结果
  // 因为 @address 包含验证错误信息，所以 render 出来的 HTML 也包含验证信息
  $('form.new_address').replaceWith(html);
<% end %>

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form', resource: @resource %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<p id="notice"><%= notice %></p>

<h6>

<%= form_tag("/resources/search", method: "get") do %>

  <%= label_tag(:search_id, "资源") %>
  <!-- <%= text_field_tag(:search_id1) %> -->
  <%= select_tag :search_id, options_for_select(Resource.resourcetypes.keys) %>
  <%= submit_tag("查询") %>

  <!-- <%= link_to '搜索', search_resources_path %>
  <%= link_to '类型', resources_path(:resourcetype_id => 2) %>
  <%= link_to '类型', resources_path(:resourcetype_id => params[:search_id]) %> -->
<% end %>

</h6>


<table  class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">编号</th>
      <th scope="col">名称</th>
      <th scope="col">类型</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>

      <tr>
        <th scope="row"><%= link_to resource.code,resource %></th>
        <td><%= resource.name %></td>
        <td><%= resource.resourcetype %></td>
        <!-- <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td> -->
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<br>

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= render 'form', resource: @resource %>

<%= link_to 'Back', resources_path %>

app/views/resources/new.js.erb
bootbox1.alert("hello world!")
rr
var html = "<%= j(render('formajax', remote: true)) %>";
// bootbox 弹窗插件 http://bootboxjs.com/

bootbox.dialog({
  title: "新增联系地址",
  message: html
});

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @resource.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @resource.name %>
</p>

<p>
  <strong>Resourcetype:</strong>
  <%= @resource.resourcetype %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>