config/routes.rb
Rails.application.routes.draw do
  resources :migrations
  root 'businesses#index', as: 'businesses_index'

  resources :businessunits, :transactionunits, :activeunits
  resources :businessflows, :transactionflows, :activeflows


  resources :resources do
    get 'search', on: :collection
  end

  resources :resourceslines

  resources :businesses do
    resources :businessflows
  end



  resources :actives do
    resources :resourceslines
    get 'clone', on: :member
    get 'copyform', on: :member
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_resourcesline.html.erb
<table>
  <tr>
    <td class="rlid"><%= resourcesline.id %></td>
    <td class="rlcode"><%= resourcesline.resource.code %></td>
    <td class="rlname"><%= resourcesline.resource.name %></td>
    <td class="rlquan"><%= resourcesline.quantity %></td>
    <td class="rlpric"><%= resourcesline.price %></td>
    <td class="rlpric"><%= resourcesline.total %></td>
    <td class="rlcost"><%= resourcesline.cost %></td>
    <td class="rlvatg"><%= resourcesline.vatgroup %></td>
    <td class="rlwhsc"><%= resourcesline.whscode %></td>
    <td class="rlstat"><%= resourcesline.status %></td>
    <!-- <td><%= link_to 'Edit', resourcesline %></td> -->
    <td><%= link_to 'Edit', edit_resourcesline_path  %></td>

    <td><%= link_to 'Destroy', [resourcesline.active, resourcesline],
    method: :delete, data: { confirm: 'Are you sure?' } %></td>

  </tr>

</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyWork</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  </head>

  <body >
    <header>
      <div class="container">
        <nav class="navbar navbar-expand-md navbar-light bg-transparent">
            <a class="navbar-brand" href="#"><strong>MyWork</strong>.net</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
            </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
           <ul class="navbar-nav mr-auto">
           <li class="nav-item active">
            <a class="nav-link" href="businesses">首页 <span class="sr-only">(current)</span></a>
           </li>
           <li class="nav-item">
            <a class="nav-link" href=<%= resources_path %>>资源</a>
           </li>
           <li class="nav-item">
            <a class="nav-link" href=<%= businesses_path %>>商务</a>
           </li>
           <li class="nav-item">
            <a class="nav-link" href=<%= actives_path %>>活动</a>
           </li>
           <li class="nav-item dropdown">
             <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               组件
             </a>
             <div class="dropdown-menu" aria-labelledby="navbarDropdown">
               <a class="dropdown-item" href=<%= businessunits_path %>>商务</a>
               <a class="dropdown-item" href=<%= transactionunits_path %>>交易</a>
               <a class="dropdown-item" href=<%= activeunits_path %>>活动</a>
             </div>
           </li>
           <li class="nav-item dropdown">
             <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               流程
             </a>
             <div class="dropdown-menu" aria-labelledby="navbarDropdown">
               <a class="dropdown-item" href=<%= businessflows_path %>>商务</a>
               <a class="dropdown-item" href=<%= transactionflows_path %>>交易</a>
               <a class="dropdown-item" href=<%= activeflows_path %>>活动</a>
             </div>
           </li>


          </ul>
            <!-- <form class="form-inline my-2 my-lg-0">
             <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
             <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form> -->
          </div>
        </nav>
      </div>
    </header>

    <div class="container-fluid">
     <%= yield %>
    </div>

    <div class="bottom container">

    </div>

    <footer class="container">
        <nav class="navbar navbar-expand-md navbar-light bg-transparent">
          关于 | 故事 | 联系 | 文档  2018©mywork ICP备210037号
        </nav>


    </footer>

  <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://cdn.bootcss.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>